name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Terraform Init & Validate
      run: |
        terraform init
        terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve

    # - name: Terraform Destroy
    #   if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    #   run: terraform destroy -auto-approve
